### PR TITLE
Correct traffic_class_name population from tclass_names

### PR DESCRIPTION
**Pull request by davegreen**
Fixes error raised in #10

### CODE REVIEW

**Review by adamwilkins-hpe — COMMENTED** [review]
I don't have a current environment to test the telemetry demo to test the changes you suggest. Please update your local copy repo for now until someone can test this change.  Thanks for contributing!

**Comment by alexamayahpe** [comment]
@adamwilkins-hpe, are you asking if someone who has pyedgeconnect running can validate these changes before merging? Or it has been tested and we need to approve to merge into the development branch.

**Comment by adamwilkins-hpe** [comment]
@alexamayahpe No, this is about the telemetry demo environment. I have pyedgeconnect, but there is quite a bit of logical infrastructure required for the telemetry demo e.g. Docker, Grafana, InfluxDB, and Redis. As a result, I cannot test anything to do with that at this time.

**Comment by adamwilkins-hpe** [comment]
I went ahead and added this to the development branch.

**Pull request closed without merging**
